#!/bin/sh

cat << EOF
################################################################################
# buildroot-sdk-version
################################################################################
BUILDROOT_SDK_VERSION="$(dpkg-query -W -f='${Version}\n' buildroot-sdk)"
$( [ -f /opt/buildroot-sdk/sdk-info ] &&
  cat /opt/buildroot-sdk/sdk-info
)
################################################################################
EOF
