#!/bin/sh

docker build --progress=plain -t buildroot-builder .
docker run \
  --interactive \
  --tty \
  --volume "${PWD}:/build" \
  --workdir /build \
  --entrypoint /build/build.sh buildroot-builder $@
